version: '3.8'

services:
  install-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app-out  # Récupère les fichiers générés localement
    command: ["cp", "-r", "/app/package-lock.json", "/app-out/"]
    profiles:
      - install-only  # Ajoute ce service au profil "install-only"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"  # Expose le serveur de dev React sur le port 5173
    environment:
      - CHOKIDAR_USEPOLLING=true  # Résout les problèmes de hot-reloading dans les conteneurs
    volumes:
      - ./frontend:/app  # Montre les fichiers locaux pour le hot-reloading
      - /app/node_modules  # Empêche le conflit avec les dépendances locales
    stdin_open: true
    tty: true


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend:/app
    stdin_open: true
    tty: true