name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - master

env:
  VITE_CHAT_BACKEND_URL: ${{ secrets.VITE_CHAT_BACKEND_URL }}
  VITE_MAIL_BACKEND_URL: ${{ secrets.VITE_MAIL_BACKEND_URL }}
  VITE_CHAT_BACKEND_URL_VARS: ${{ vars.VITE_CHAT_BACKEND_URL }}
  VITE_MAIL_BACKEND_URL_VARS: ${{ vars.VITE_MAIL_BACKEND_URL }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: |
          cd frontend
          npm install
      
      - name: Set environment variables
        run: |
          echo "VITE_CHAT_BACKEND_URL=$VITE_CHAT_BACKEND_URL" > frontend/.env
          echo "VITE_MAIL_BACKEND_URL=$VITE_MAIL_BACKEND_URL" >> frontend/.env
          echo "VITE_CHAT_BACKEND_URL_VARS=$VITE_CHAT_BACKEND_URL_VARS" >> frontend/.env
          echo "VITE_MAIL_BACKEND_URL_VARS=$VITE_MAIL_BACKEND_URL_VARS" >> frontend/.env
      - name: Debug .env content
        run: cat frontend/.env

      - name: Build Project
        run: |
          cd frontend
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: frontend/dist
          clean: true
          single-commit: true
          exclude: ".nojekyll"
